Wait(Event(worldInfo.PlayerBorn))
Cat:NewClearState(0)
Cat:AddAnim("Sitting", false, true, 1, 1)
Wait(Event(door.Used))
Wait(Delay(2))
sound:PlayOnce()
Cat:NewClonedState(0.25)
Cat:AddAnim("Cat_Run_02", false, true, 1, 1)
CatMover:PlayAnim("Default")
Wait(Delay(3))
sound2:PlayOnce()
Wait(Delay(0.5))
Cat:Disappear()