TVAnimator:StartAnimation("Off")
TVPowerButtonAnimator:StartAnimation("Pulsating")
TV:EnableUsage()
Wait(Event(TV.Used))
button:PlayOnce()
Wait(Delay(1.5))
TVAnimator:StartAnimation("On")
TVPowerButtonAnimator:StartAnimation("On")
worldInfo:ForceMusic("Event", resGameMusic)
